# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=60)),
                ('sell_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('order_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='suppliers.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('quantity_withdraw', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='stock.Product')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='productshipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='stock.Product'),
        ),
        migrations.AddField(
            model_name='productshipment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.Shipment'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.Stock'),
        ),
    ]
