# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=60)),
                ('observation', models.TextField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='addresses.Address')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
