# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'Rua'), (2, 'Avenida'), (3, 'Travessa')])),
                ('place_name', models.CharField(max_length=60)),
                ('number', models.IntegerField(null=True)),
                ('complement', models.CharField(max_length=20, null=True)),
                ('neighborhood', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
